FROM julia:tail

MAINTAINER Julianne <juliannebot@gmail.com>

WORKDIR /root

ENV JULIA_PKGDIR /usr/local/julia/share/julia/site

ADD TARGET TARGET

RUN cd julia && git checkout master && git pull && git checkout $(cat ../TARGET) && make clean && make -j"$(nproc --all)"

RUN ./julia/julia -e 'Pkg.update()'
